services:
  db:
    image: postgres:16-alpine
    container_name: biblioteca-db
    restart: unless-stopped
    # Carga variables desde .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # Acelera arranque en discos lentos y evita fsync costoso en dev (solo DEV)
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1",
        ]
      interval: 3s
      timeout: 2s
      retries: 20

volumes:
  pg_data: {}
